[phases.setup]
# Ensure Python and pip are available in the image
nixPkgs = ["python311", "python311Packages.pip", "bash"]

[phases.install]
cmds = [
  # Create a virtualenv so pip installs do not touch the Nix store
  "virtualenv -p python /app/venv || python -m venv /app/venv",
  # Install dependencies inside the venv
  "/app/venv/bin/pip install --no-cache-dir --upgrade pip setuptools wheel",
  "/app/venv/bin/pip install --no-cache-dir -r backend/requirements.txt"
]

[variables]
PYTHONUNBUFFERED = "1"
PYTHONDONTWRITEBYTECODE = "1"
PYTHONPATH = "."

[start]
cmd = "/app/venv/bin/uvicorn backend.app:app --host 0.0.0.0 --port $PORT"
